{{- if or (and (not .Values.database.existingSecret.name) .Values.database.url) (and (not .Values.jwt.existingSecret.name) .Values.jwt.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pertisk-gits.fullname" . }}
  labels:
    {{- include "pertisk-gits.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.database.existingSecret.name) .Values.database.url }}
  database-url: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if and (not .Values.jwt.existingSecret.name) .Values.jwt.secret }}
  jwt-secret: {{ .Values.jwt.secret | quote }}
  {{- end }}
{{- end }}
