{{- if and .Values.runnerToken (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pertisk-runner.fullname" . }}
  labels:
    {{- include "pertisk-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.runnerToken | quote }}
{{- end }}
