on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]

jobs:
  build-docker:
    runs-on: docker
    needs: []
    timeout_minutes: 30
    steps:
      - name: Build
        env:
          PERTISK_FORCE_DOCKER_BUILD: "1"
        run: make package-runner-amd64 VERSION=1.0.0
