const EXTENSION_LANGUAGE: Record<string, string> = {
  rs: 'rust',
  ts: 'ts',
  tsx: 'tsx',
  js: 'js',
  jsx: 'jsx',
  mjs: 'js',
  cjs: 'js',
  py: 'py',
  go: 'go',
  java: 'java',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  cs: 'csharp',
  rb: 'ruby',
  php: 'php',
  swift: 'swift',
  kt: 'kotlin',
  kts: 'kotlin',
  scala: 'scala',
  sql: 'sql',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'bash',
  yml: 'yaml',
  yaml: 'yaml',
  json: 'json',
  md: 'md',
  markdown: 'md',
  html: 'html',
  htm: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'scss',
  less: 'css',
  toml: 'toml',
  graphql: 'graphql',
  gql: 'graphql',
  lua: 'lua',
  r: 'r',
  vue: 'html',
  svelte: 'html',
  xml: 'xml',
  ini: 'ini',
  proto: 'protobuf',
  wasm: 'wasm',
  vim: 'vim',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hs: 'haskell',
  clj: 'clojure',
  dart: 'dart',
  zig: 'zig',
  tf: 'hcl',
  hcl: 'hcl',
  lock: 'json',
}

export function languageFromPath(path: string): string {
  const fileName = path.split('/').pop()?.toLowerCase() ?? ''

  if (fileName === 'dockerfile') return 'docker'
  if (fileName === 'makefile') return 'makefile'
  if (fileName.startsWith('.env')) return 'bash'

  const ext = fileName.includes('.') ? (fileName.split('.').pop() ?? '') : ''
  return EXTENSION_LANGUAGE[ext] ?? 'text'
}
