ALTER TABLE runners
    ADD COLUMN IF NOT EXISTS version VARCHAR(32),
    ADD COLUMN IF NOT EXISTS host_ip VARCHAR(45),
    ADD COLUMN IF NOT EXISTS host_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS cpu_cores INTEGER,
    ADD COLUMN IF NOT EXISTS memory_total_mb BIGINT,
    ADD COLUMN IF NOT EXISTS memory_used_mb BIGINT,
    ADD COLUMN IF NOT EXISTS disk_total_mb BIGINT,
    ADD COLUMN IF NOT EXISTS disk_free_mb BIGINT,
    ADD COLUMN IF NOT EXISTS last_job_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS last_job_status VARCHAR(32),
    ADD COLUMN IF NOT EXISTS last_job_at TIMESTAMPTZ;
