[package]
name = "pertisk-runner"
version.workspace = true
edition.workspace = true

[[bin]]
name = "pertisk-runner"
path = "src/main.rs"

[dependencies]
pertisk-cicd = { path = "../cicd" }
pertisk-git = { path = "../git" }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { version = "4", features = ["derive", "env"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = "0.33"
bytes = "1"
tempfile = "3"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
