[package]
name = "pertisk-git"
version.workspace = true
edition.workspace = true

[lib]
name = "pertisk_git"
path = "src/lib.rs"

[[bin]]
name = "pertisk-git-http"
path = "src/bin/git-http.rs"

[dependencies]
pertisk-domain = { path = "../domain" }
anyhow = { workspace = true }
argon2 = { workspace = true }
axum = { workspace = true }
bytes = "1"
dotenvy = { workspace = true }
futures-util = "0.3"
http-body-util = "0.1"
serde = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["io"] }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
