[package]
name = "pertisk-domain"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
